### ISSUE TITLE
Início do desenvolvimento da criação de conta de user(funcionário)

### ISSUE THREAD

**Issue by DaniloFranca01** [DaniloFranca01/CaelumEAP#5]
Desenvolvimento será iniciado

**Comment by adrianogs6** [comment]
Confirmo que participarei da solução desta issue.

**Comment by DaniloFranca01** [comment]
[Concluido](https://github.com/DaniloFranca01/CaelumEAP/commit/6040d13946cba7548f19e9de51d8f3b8d03fab93)
