### ISSUE TITLE
Criação de testes de user(funcionário)

### ISSUE THREAD

**Issue by DaniloFranca01** [DaniloFranca01/CaelumEAP#6]
A criação dos primeiros testes será iniciada

**Comment by fernandofeoli** [comment]
Confirmo que participarei da solução desta issue.

**Comment by gstadtler** [comment]
Testes criados e entregue conforme o [commit](https://github.com/DaniloFranca01/CaelumEAP/commit/6992321cb7ebd89d7ebcbac0c372047fb2bd1dea)
