### ISSUE TITLE
Criação do planejamento

### ISSUE THREAD

**Issue by DaniloFranca01** [DaniloFranca01/CaelumEAP#7]
Criação do planejamento no formato GQM

**Comment by bartagoitia1977** [comment]
Confirmo a participação na solução desta "issue".

**Comment by bartagoitia1977** [comment]
Documento [GQM](https://github.com/DaniloFranca01/CaelumEAP/blob/master/Documenta%C3%A7%C3%A3o/GQM%20-%20CAELUM%20EAP.docx) entregue
