### ISSUE TITLE
Criação de testes do cadastro de pacientes

### ISSUE THREAD

**Issue by DaniloFranca01** [DaniloFranca01/CaelumEAP#8]
A criação dos primeiros testes será iniciada

**Comment by gstadtler** [comment]
Confirmo que participarei da solução dessa issue.

**Comment by gstadtler** [comment]
Testes criados e entregue conforme o [commit](https://github.com/DaniloFranca01/CaelumEAP/commit/301bd0cd762d59877ba0a5f3747cb02d3d21fa2c)
