### ISSUE TITLE
Início do desenvolvimento cadastro de pacientes

### ISSUE THREAD

**Issue by DaniloFranca01** [DaniloFranca01/CaelumEAP#9]
O desenvolvimento será iniciado

**Comment by ghost** [comment]
Fico responsável por esta etapa

**Comment by DaniloFranca01** [comment]
Cadastro criado e entregue conforme o [commit](https://github.com/DaniloFranca01/CaelumEAP/commit/187334cb6faabfdef5431d7dab184c06dd207d8c)
